---
name: JavaScript-Code
version: 0.04
author:
  - 'Sascha Kiefer, C<esskar@cpan.org>'
abstract: A JavaScript Code Framework
license: perl
requires:
  Class::Accessor::Chained::Fast: 0
  Scalar::Util: 1.14
provides:
  JavaScript::Code:
    file: lib/JavaScript/Code.pm
    version: 0.04
  JavaScript::Code::Accessor:
    file: lib/JavaScript/Code/Accessor.pm
    version: 0.03
  JavaScript::Code::Array:
    file: lib/JavaScript/Code/Array.pm
    version: 0.02
  JavaScript::Code::Block:
    file: lib/JavaScript/Code/Block.pm
    version: 0.04
  JavaScript::Code::Element:
    file: lib/JavaScript/Code/Element.pm
    version: 0.02
  JavaScript::Code::Expression:
    file: lib/JavaScript/Code/Expression.pm
    version: 0.02
  JavaScript::Code::Expression::Arithmetic:
    file: lib/JavaScript/Code/Expression/Arithmetic.pm
    version: 0.01
  JavaScript::Code::Expression::Node:
    file: lib/JavaScript/Code/Expression/Node.pm
    version: 0.01
  JavaScript::Code::Expression::Node::Arithmetic:
    file: lib/JavaScript/Code/Expression/Node/Arithmetic.pm
    version: 0.01
  JavaScript::Code::Expression::Op:
    file: lib/JavaScript/Code/Expression/Op.pm
    version: 0.01
  JavaScript::Code::Expression::Op::Addition:
    file: lib/JavaScript/Code/Expression/Op/Addition.pm
    version: 0.01
  JavaScript::Code::Expression::Op::Division:
    file: lib/JavaScript/Code/Expression/Op/Division.pm
    version: 0.01
  JavaScript::Code::Expression::Op::Multiplication:
    file: lib/JavaScript/Code/Expression/Op/Multiplication.pm
    version: 0.01
  JavaScript::Code::Expression::Op::Subtraction:
    file: lib/JavaScript/Code/Expression/Op/Subtraction.pm
    version: 0.01
  JavaScript::Code::Expression::Op::Term:
    file: lib/JavaScript/Code/Expression/Op/Term.pm
    version: 0.01
  JavaScript::Code::Hash:
    file: lib/JavaScript/Code/Hash.pm
    version: 0.01
  JavaScript::Code::Number:
    file: lib/JavaScript/Code/Number.pm
    version: 0.04
  JavaScript::Code::String:
    file: lib/JavaScript/Code/String.pm
    version: 0.03
  JavaScript::Code::Type:
    file: lib/JavaScript/Code/Type.pm
    version: 0.02
  JavaScript::Code::Value:
    file: lib/JavaScript/Code/Value.pm
    version: 0.01
  JavaScript::Code::Variable:
    file: lib/JavaScript/Code/Variable.pm
    version: 0.04
generated_by: Module::Build version 0.2611
